name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Create Buildx Cache Directory
        run: |
          mkdir -p docker_storage

      - name: Set up Docker Buildx Cache
        uses: actions/cache@v3
        with:
          path: docker_storage
          key: ${{ runner.os }}-cache-${{ github.sha }}

      - name: Build Docker image
        run: |
          docker build --file Dockerfile --tag db-admin:latest .

      - name: Save Docker image in cache
        run: |
          docker save -o docker_storage/db-admin.tar db-admin:latest

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Load Docker image from cache
        uses: actions/cache@v3
        with:
          key: ${{ runner.os }}-cache-${{ github.sha }}
          path: docker_storage

      - name: Load Docker image
        run: |
          docker load -i docker_storage/db-admin.tar

      - name: Create docker network
        run: |
          docker network create db-admin

      - name: Run PostgreSQL container
        run: |
          docker run -d --name postgres --network db-admin -e POSTGRES_USER=user -e POSTGRES_PASSWORD=1234 postgres:latest

      - name: Run db-admin container
        run: |
          docker run -d --name db-admin --network db-admin db-admin:latest

      - name: Run newman tests
        run: |
          docker run --rm --network db-admin -v $(pwd)/postman:/postman postman/newman run /postman/collection.json -e /postman/environment.json --env-var 'host=db-admin:3000'

      - name: Stop containers
        run: |
          docker stop db-admin
          docker stop postgres

      - name: Remove containers
        run: |
          docker rm db-admin
          docker rm postgres
